name: 'Daily Version'
description: 'Creates a new tag using the format Y.M.D, but only if HEAD isn’t already tagged'
outputs:
  created:
    description: 'If it exists, a new tag has been created'
  version:
    description: 'The latest version tag, either pre-existing or just created'
runs:
  using: 'node12'
  main: 'distribution/index.js'
