name: Test

on:
  - push

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Action
        id: Version
        uses: ./
      - name: Test the action by deleting the tag it supposedly created
        run: |
          if [ yes = ${{ steps.Version.outputs.created }} ]; then
            git push --delete origin ${{ steps.Version.outputs.version }}
          fi
