name: Test

on:
  push:
    # paths:
    #   - distribution/index.js

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Action
        id: Version
        uses: ./
      - name: Test the action by deleting the tag it supposedly created
        run: |
          # Test outputs
          test ${{ steps.Version.outputs.version }}
          test ${{ steps.Version.outputs.created }}

          # Show and test ENVs
          echo DAILY_VERSION=$DAILY_VERSION
          echo DAILY_VERSION_CREATED=$DAILY_VERSION_CREATED
          test $DAILY_VERSION
          test $DAILY_VERSION_CREATED

          # Test tag
          git show-ref --tags "refs/tags/$DAILY_VERSION"
          git push --delete origin "$DAILY_VERSION"
