name: Test

on:
  push:
    paths:
      - distribution/index.js
      - .github/workflows/test.yml

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Action
        id: Version
        uses: ./
      - name: Test the action
        run: |
          # Test outputs
          test ${{ steps.Version.outputs.version }}
          test ${{ steps.Version.outputs.created }}

          # Test ENVs
          test $DAILY_VERSION
          test $DAILY_VERSION_CREATED

          # Test tag
          git show-ref --tags "refs/tags/$DAILY_VERSION"
      - name: Run Action twice
        id: Version2
        uses: ./
      - name: Test the action again
        run: |
          # Test outputs
          test ${{ steps.Version2.outputs.version }}
          test -v ${{ steps.Version2.outputs.created }}

          # Test ENVs
          test $DAILY_VERSION
      - name: Cleanup
        if: always()
        run: |
          git push --delete origin "${{ steps.Version.outputs.version }}"
